// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaginationLearningFietkau.Models;

#nullable disable

namespace PaginationLearningFietkau.Migrations
{
    [DbContext(typeof(ItemCtx))]
    partial class ItemCtxModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("PaginationLearningFietkau.Models.Perishable", b =>
                {
                    b.Property<int>("PerishableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("PerishableID");

                    b.ToTable("Perishables");
                });
#pragma warning restore 612, 618
        }
    }
}
